import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowLeft, ArrowRight, Check, Compass, Heart, MapPin, Palmtree, PartyPopper, Plane, RefreshCw, Sparkles, Sun, Users, Waves} from 'lucide-react';
import './styles.css';

const destinations=['Sardegna','Mykonos','Ibiza','Puglia','Sicily','Marbella','St. Tropez','Çeşme','Amalfi Coast','Mallorca','Santorini','Hvar','Dubai','Miami','Bodrum','Cap Ferret','Milos','Crete','Corsica'];
const companions=["Your ex","Your friend’s ex","Your crush"];
const activities=['Clubbing','Boating','Beach day','Romantic restaurant','Art gallery','Sunset cocktails','Sailing','Beach club','Old-town adventure','Arguing','Wine tasting','Bike ride'];
const pick=a=>a[Math.floor(Math.random()*a.length)];

function Scratch({children,label,onReveal,resetKey}){
 const ref=useRef(null),drawing=useRef(false),last=useRef(null),revealed=useRef(false);
 useEffect(()=>{const canvas=ref.current,rect=canvas.parentElement.getBoundingClientRect(),ratio=Math.min(devicePixelRatio||1,2);canvas.width=rect.width*ratio;canvas.height=rect.height*ratio;canvas.style.width=rect.width+'px';canvas.style.height=rect.height+'px';const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.scale(ratio,ratio);const gradient=ctx.createLinearGradient(0,0,rect.width,rect.height);gradient.addColorStop(0,'#9ba2a7');gradient.addColorStop(.28,'#e7eaeb');gradient.addColorStop(.55,'#8d969c');gradient.addColorStop(.78,'#d8dcde');gradient.addColorStop(1,'#697279');ctx.fillStyle=gradient;ctx.fillRect(0,0,rect.width,rect.height);ctx.fillStyle='rgba(255,255,255,.35)';for(let i=0;i<450;i++)ctx.fillRect(Math.random()*rect.width,Math.random()*rect.height,1.3,1.3);ctx.fillStyle='rgba(24,31,34,.38)';ctx.font='900 11px Inter';ctx.textAlign='center';for(let y=22;y<rect.height;y+=34)for(let x=18;x<rect.width+55;x+=72){ctx.save();ctx.translate(x,y);ctx.rotate(-.2);ctx.fillText(label,0,0);ctx.restore()}ctx.globalCompositeOperation='destination-out';revealed.current=false},[label,resetKey]);
 const point=e=>{const r=ref.current.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};
 const move=e=>{if(!drawing.current)return;const canvas=ref.current,ctx=canvas.getContext('2d'),p=point(e),ratio=canvas.width/canvas.getBoundingClientRect().width;ctx.save();ctx.scale(ratio,ratio);ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=38;ctx.beginPath();ctx.moveTo(last.current?.x??p.x,last.current?.y??p.y);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.restore();last.current=p};
 const finish=()=>{drawing.current=false;last.current=null;if(revealed.current)return;const canvas=ref.current,ctx=canvas.getContext('2d'),data=ctx.getImageData(0,0,canvas.width,canvas.height).data;let clear=0,total=0;for(let i=3;i<data.length;i+=80){total++;if(data[i]<40)clear++}if(clear/total>.42){revealed.current=true;ctx.clearRect(0,0,canvas.width,canvas.height);onReveal()}};
 return <div className="scratch-zone">{children}<canvas ref={ref} aria-label={`Scratch to reveal ${label.toLowerCase()}`} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drawing.current=true;last.current=point(e);move(e)}} onPointerMove={move} onPointerUp={finish} onPointerCancel={finish}/></div>
}

function Landing({play}){return <main className="landing"><header className="hero summer"><span className="mini">YOUR SUMMER STORY STARTS HERE</span><div className="sun-mark"><Sun/></div><h1>SUMMER<br/><em>SCRATCHERS</em></h1><p>Where will you go on vacation this summer?</p></header><section className="intro"><div className="issue"><span>THE 2026 EDITION</span><small>ONE TRIP · THREE REVEALS</small></div><div className="hero-ticket"><div className="ticket-ribbon"><span>THE GREAT SUMMER ESCAPE</span><b>PLAY</b></div><div className="ticket-content"><div className="globe"><Palmtree/></div><div><small>SCRATCH YOUR STORY</small><h2>DESTINATION<br/>UNKNOWN</h2><p>Reveal where, who and what.</p></div><ArrowRight/></div><button onClick={play}>START SCRATCHING <Sparkles/></button></div><div className="destinations"><span>IN THE MIX</span><div>{destinations.map(d=><i key={d}>{d}</i>)}</div></div></section><footer className="legal">A playful summer vacation generator. No purchases or real prizes.</footer></main>}

const labels=[{key:'place',number:'01',title:'WHERE',hint:'Your summer destination',Icon:MapPin},{key:'person',number:'02',title:'WITH WHO',hint:'Your travel companion',Icon:Heart},{key:'activity',number:'03',title:'DOING WHAT',hint:'Your main character moment',Icon:PartyPopper}];
function Game({back}){const [reset,setReset]=useState(0),[result,setResult]=useState(()=>({place:pick(destinations),person:pick(companions),activity:pick(activities)})),[revealed,setRevealed]=useState({});const newTrip=()=>{setResult({place:pick(destinations),person:pick(companions),activity:pick(activities)});setRevealed({});setReset(v=>v+1)};const complete=Object.keys(revealed).length===3;return <main className="game"><nav><button onClick={back}><ArrowLeft/> Home</button><div><span>SUMMER</span><b>’26</b></div></nav><section className="game-stage"><article className="vacation-card"><header><Plane/><div><span>SUMMER SCRATCHERS</span><h2>WHERE WILL YOU GO?</h2></div><Sun/></header><p className="instructions">Scratch all three panels to reveal your summer story</p><div className="reveals">{labels.map(({key,number,title,hint,Icon})=><section className={'reveal '+(revealed[key]?'is-revealed':'')} key={key}><div className="reveal-label"><b>{number}</b><div><span>{title}</span><small>{hint}</small></div><Icon/></div><Scratch label={title} resetKey={reset} onReveal={()=>setRevealed(v=>({...v,[key]:true}))}><div className="answer"><Icon/><strong>{result[key]}</strong><span>{key==='place'?'Pack your bags':key==='person'?'This could get interesting':'Your summer highlight'}</span></div></Scratch></section>)}</div><footer><span>EUROPEAN SUMMER EDITION</span><span>GOOD VIBES ONLY</span></footer></article>{complete&&<div className="result"><Check/><div><small>YOUR SUMMER STORY</small><p>You’re going to <b>{result.place}</b> with <b>{result.person.toLowerCase()}</b> for <b>{result.activity.toLowerCase()}</b>.</p></div></div>}<button className="reset" onClick={newTrip}><RefreshCw/> Scratch a new trip</button></section></main>}
function App(){const [playing,setPlaying]=useState(false);return <div className="app-shell">{playing?<Game back={()=>setPlaying(false)}/>:<Landing play={()=>setPlaying(true)}/>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
