import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowLeft, ArrowRight, Camera, Check, CircleDollarSign, Coins, Gem, Globe2, Luggage, Plane, RotateCcw, Sparkles, Star, Sun, Umbrella} from 'lucide-react';
import './styles.css';

const cards=[
 {id:'estate',eyebrow:"VIVA L’ESTATE",title:'Summer Bonus',sub:'Premio massimo €500.000',price:'€5',tone:'orange',Icon:Sun},
 {id:'turista',eyebrow:'IL TURISTA PER SEMPRE',title:'Travel for life',sub:'€6.000 al mese per 20 anni',price:'€5',tone:'yellow',Icon:Globe2},
 {id:'numeri',eyebrow:'NUMERI FORTUNATI',title:'Lucky Sevens',sub:'Trova i numeri vincenti',price:'€3',tone:'red',Icon:Gem},
];

function Scratch({children,label='GRATTA QUI',className='',onComplete,resetKey}){
 const ref=useRef(null),drawing=useRef(false),last=useRef(null),done=useRef(false);
 useEffect(()=>{const c=ref.current,box=c.parentElement,r=box.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);c.width=r.width*d;c.height=r.height*d;c.style.width=r.width+'px';c.style.height=r.height+'px';const x=c.getContext('2d',{willReadFrequently:true});x.scale(d,d);const g=x.createLinearGradient(0,0,r.width,r.height);g.addColorStop(0,'#7f8791');g.addColorStop(.35,'#e6e9eb');g.addColorStop(.65,'#979fa8');g.addColorStop(1,'#616975');x.fillStyle=g;x.fillRect(0,0,r.width,r.height);x.fillStyle='rgba(255,255,255,.3)';for(let i=0;i<400;i++)x.fillRect(Math.random()*r.width,Math.random()*r.height,1.5,1.5);x.fillStyle='rgba(28,35,42,.35)';x.font='800 12px Inter';x.textAlign='center';for(let y=24;y<r.height;y+=38)for(let p=25;p<r.width;p+=76){x.save();x.translate(p,y);x.rotate(-.22);x.fillText(label,0,0);x.restore()}x.globalCompositeOperation='destination-out';done.current=false;},[resetKey,label]);
 const point=e=>{const r=ref.current.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};
 const scratch=e=>{if(!drawing.current)return;const c=ref.current,x=c.getContext('2d'),p=point(e),d=c.width/c.getBoundingClientRect().width;x.save();x.scale(d,d);x.lineCap='round';x.lineJoin='round';x.lineWidth=34;x.beginPath();x.moveTo(last.current?.x??p.x,last.current?.y??p.y);x.lineTo(p.x,p.y);x.stroke();x.restore();last.current=p};
 const finish=()=>{drawing.current=false;last.current=null;if(done.current)return;const c=ref.current,x=c.getContext('2d'),data=x.getImageData(0,0,c.width,c.height).data;let clear=0,total=0;for(let i=3;i<data.length;i+=80){total++;if(data[i]<40)clear++}if(clear/total>.46){done.current=true;x.clearRect(0,0,c.width,c.height);onComplete?.()}};
 return <div className={'scratch '+className}>{children}<canvas ref={ref} aria-label="Scratch area" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drawing.current=true;last.current=point(e);scratch(e)}} onPointerMove={scratch} onPointerUp={finish} onPointerCancel={finish}/></div>
}

const Prize=({icon:Icon=Sun,name,amount,hot})=><div className={'prize '+(hot?'hot':'')}><Icon/><b>{name}</b><span>{amount}</span></div>;
function Estate({resetKey,onWin}){return <article className="ticket estate"><TicketHead card={cards[0]}/><p className="rule">Trova 2 simboli uguali per vincere il premio</p><Scratch resetKey={resetKey} onComplete={()=>onWin(50)}><div className="prize-grid"><Prize name="SOLE" amount="€50" hot/><Prize name="SOLE" amount="€50" hot/><Prize icon={Umbrella} name="SPIAGGIA" amount="€10"/><Prize icon={Plane} name="VIAGGIO" amount="€500"/><Prize icon={Camera} name="FOTO" amount="€100"/><Prize icon={Luggage} name="VALIGIA" amount="€20"/></div></Scratch><TicketFoot text="PREMIO MASSIMO €500.000"/></article>}
function Turista({resetKey,onWin}){return <article className="ticket turista"><TicketHead card={cards[1]}/><p className="rule dark">Confronta i numeri e vinci il premio</p><section className="game-body"><h4>NUMERI VINCENTI</h4><Scratch resetKey={resetKey} label="NUMERI"><div className="winning"><i>14</i><i>42</i></div></Scratch><h4>I TUOI NUMERI</h4><Scratch resetKey={resetKey} label="GRATTA" onComplete={()=>onWin(150)}><div className="number-grid">{[['14','€100'],['07','€5'],['22','€10'],['42','€50'],['88','€20'],['19','€500']].map(([n,p])=><div className={n==='14'||n==='42'?'match':''} key={n}><b>{n}</b><small>{p}</small></div>)}</div></Scratch><div className="bonus"><span>BONUS VIAGGIO</span><Scratch resetKey={resetKey} label="BONUS"><Luggage/></Scratch></div></section><TicketFoot text="UNA VACANZA CHE DURA PER SEMPRE"/></article>}
function Numeri({resetKey,onWin}){return <article className="ticket numeri"><TicketHead card={cards[2]}/><p className="rule">Trova una stella e vinci il premio</p><Scratch resetKey={resetKey} onComplete={()=>onWin(100)}><div className="rows">{[['12','45','77','€10'],['03','★','29','€50'],['61','18','90','€5'],['33','44','55','€100']].map((r,i)=><div className="row" key={i}><small>GIOCATA {i+1}</small>{r.slice(0,3).map(n=><i className={n==='★'?'star':''} key={n}>{n==='★'?<Star/>:n}</i>)}<b>{r[3]}</b></div>)}</div></Scratch><div className="mult"><span>MOLTIPLICATORE <strong>BONUS</strong></span><Scratch resetKey={resetKey} label="?"><b>X2</b></Scratch></div><TicketFoot text="PREMIO MASSIMO €500.000"/></article>}
function TicketHead({card}){return <header className="ticket-head"><span>GRATTA & VINCI</span><h2>{card.eyebrow}</h2><b>{card.price}</b></header>}
const TicketFoot=({text})=><footer className="ticket-foot"><span>{text}</span><span>SIMULAZIONE · 18+</span></footer>;

function Picker({select}){return <main className="picker"><header className="hero"><span className="mini">ITALIA · EDIZIONE DIGITALE</span><h1>GRATTA<br/><em>& VINCI</em></h1><p>Scegli il tuo biglietto fortunato</p></header><section className="deck"><div className="section-title"><span>BIGLIETTI</span><small>3 disponibili</small></div>{cards.map((c,i)=><button className={'card-option '+c.tone} onClick={()=>select(c.id)} key={c.id}><div className="card-top"><span>{c.eyebrow}</span><b>{c.price}</b></div><div className="card-main"><div className="icon"><c.Icon/></div><div><small>{String(i+1).padStart(2,'0')} / 03</small><h2>{c.title}</h2><p>{c.sub}</p></div><ArrowRight/></div></button>)}</section><footer className="legal">Questo gioco è una simulazione. Non si vincono soldi veri.<br/>Gioca responsabilmente.</footer></main>}
function App(){const [active,setActive]=useState(null),[balance,setBalance]=useState(15),[reset,setReset]=useState(0),[toast,setToast]=useState(null);const win=n=>{setBalance(v=>v+n);setToast(n);setTimeout(()=>setToast(null),3200)};const open=id=>{setBalance(v=>Math.max(0,v-cards.find(c=>c.id===id).price.replace(/\D/g,'')));setActive(id);setReset(v=>v+1)};return <div className="app-shell">{!active?<Picker select={open}/>:<main className="play"><nav><button onClick={()=>setActive(null)}><ArrowLeft/> Biglietti</button><div><span>SALDO</span><b>€{balance},00</b></div></nav><div className="stage">{active==='estate'&&<Estate resetKey={reset} onWin={win}/>} {active==='turista'&&<Turista resetKey={reset} onWin={win}/>} {active==='numeri'&&<Numeri resetKey={reset} onWin={win}/>}<button className="reset" onClick={()=>setReset(v=>v+1)}><RotateCcw/> Nuovo biglietto</button></div></main>}{toast&&<div className="toast"><Check/><span>Hai vinto <b>€{toast}!</b></span></div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
